from scraping import scraping_MultiTreads
from arquivamento import FactoryArquizacao

jogos = [
    "Elden Ring",
    "Bloodborne",
    "Sekiro: Shadows Die Twice",
    "Monster Hunter: World",
    "Monster Hunter Rise",
    "Lies of P",
    "Demon’s Souls (Remake)",
    "Nioh",
    "Nioh 2",
    "Wo Long: Fallen Dynasty",
    "The Surge",
    "The Surge 2",
    "Mortal Shell",
    "Lords of the Fallen",
    "Salt and Sanctuary",
    "Blasphemous",
    "Blasphemous 2",
    "Hollow Knight",
    "Tunic",
    "Remnant: From the Ashes",
    "Remnant ii",
    "Wild Hearts",
    "Dragon’s Dogma 2",
    "Code Vein",
    "Another Crab's Treasure",
    "Enotria: The Last Song",
    "Black Myth: Wukong",
    "Sifu",
    "Thymesia",
    "Subnautica",
    "The Forgotten City",
    "Firewatch",
    "Returnal",
    "Deathloop",
    "Sable",
    "Return of the Obra Dinn",
    "Chants of Sennaar",
    "The Witness",
    "The Talos Principle",
    "The Talos Principle 2",
    "No Man's Sky",
    "Citizen Sleeper",
    "SOMA",
    "Pacific Drive",
    "DOOM Eternal",
    "Dusk",
    "Turbo Overkill",
    "Amid Evil",
    "Ghostrunner",
    "Ghostrunner 2",
    "Metal: Hellsinger",
    "BPM: Bullets Per Minute",
    "Post Void",
    "Cruelty Squad",
    "Prodeus",
    "Ion Fury",
    "Shadow Warrior 2",
    "Titanfall 2",
    "Severed Steel",
    "Roboquest",
    "Overwatch 2",
    "Paladins",
    "Valorant",
    "Apex Legends",
    "Team Fortress 2",
    "Gundam Evolution",
    "Gigantic: Rampage Edition",
    "Bleeding Edge",
    "Predecessor",
    "Smite",
    "Devil May Cry 5",
    "Bayonetta 3",
    "Metal Gear Rising: Revengeance",
    "Hades",
    "Hades II",
    "Dead Cells",
    "Nier: Automata",
    "Astral Chain",
    "God of War (Valhalla DLC)",
    "Vanquish",
    "Hi-Fi RUSH",
    "Darkest Dungeon",
    "Darkest Dungeon ii",
    "Fear & Hunger",
    "Rain World",
    "Pathologic 2",
    "STALKER 2: Heart of Chornobyl",
    "Metro Exodus",
    "Grim Dawn",
    "Armored Core VI: Fires of Rubicon",
    "Katana ZERO",
    "Hotline Miami",
    "Enter the Gungeon",
    "The Binding of Isaac: Repentance",
    "Risk of Rain 2",
    "Granblue Fantasy: Relink",
    "God Eater 3",
    "Toukiden 2",
    "Dauntless",
    "Hellblade: Senua's Sacrifice",
    "Scorn",
    "ExoPrimal",
    "Warframe",
    "Destiny 2",
    "Shadow of the Colossus",
    "Dragon's Dogma: Dark Arisen",
]

arquivo = input("Escolha do tipo de arquivo para salvar {json, excell, html, csv}")

saida = scraping_MultiTreads(jogos, 5)

FactoryArquizacao(saida, arquivo)
